module Npgsql.Generation

open Swensen.Unquote
open SqlHydra
open SqlHydra.Domain
open NUnit.Framework
open VerifyTests
open VerifyNUnit
open SqlHydra.Npgsql

// Base table vs. view.

[<TestCase("BASE TABLE", true)>]
[<TestCase("table", true)>]
[<TestCase("view", false)>]
[<TestCase("materialized view", false)>]
let ``Npgsql table types distinguish base tables from appended views`` tableType expected =
    NpgsqlSchemaProvider.isBaseTableType tableType =! expected

// Read-only detection, from a column's pg_attribute row: (attgenerated, attidentity).

[<TestCase("s", "", true, Description = "GENERATED ALWAYS AS (...) STORED")>]
[<TestCase("v", "", true, Description = "GENERATED ALWAYS AS (...) VIRTUAL (PG18+)")>]
[<TestCase("", "a", true, Description = "GENERATED ALWAYS AS IDENTITY")>]
[<TestCase("", "d", false, Description = "GENERATED BY DEFAULT AS IDENTITY is writable")>]
[<TestCase("", "", false, Description = "an ordinary column")>]
let ``A column is read-only when the database generates it, and BY DEFAULT identity does not count`` attgenerated attidentity expected =
    NpgsqlSchemaProvider.isDatabaseGenerated attgenerated attidentity =! expected

//let cfg = 
//    {
//        ConnectionString = DB.connectionString
//        OutputFile = ""
//        Namespace = "TestNS"
//        IsCLIMutable = true
//        IsMutableProperties = false
//        NullablePropertyType = NullablePropertyType.Option
//        ProviderDbTypeAttributes = true
//        TableDeclarations = false
//        Readers = Some { ReadersConfig.ReaderType = Provider.provider.DefaultReaderType } 
//        Filters = Filters.Empty
//    }

//let lazySchema = lazy NpgsqlSchemaProvider.getSchema (cfg, false)

//let getCode cfg =
//    let version = Version.get()
//    SchemaTemplate.generate cfg Provider.provider lazySchema.Value version false

//let inCode (str: string) cfg = 
//    let code = getCode cfg
//    code.Contains str =! true

//let notInCode (str: string) cfg = 
//    let code = getCode cfg
//    code.Contains str =! false

//[<Test; Ignore "Ignore">]
//let ``Print Schema``() =
//    let schema = NpgsqlSchemaProvider.getSchema (cfg, false)
//    printfn "Schema: %A" schema

//[<Test; Ignore "Ignore">]
//let ``Print Code``() =
//    getCode cfg |> printfn "%s"

//[<Test>]
//let ``Verify Generated Code``() = task {
//    let code = getCode cfg
            
//    let settings = VerifySettings()
//#if NET8_0
//    settings.UseFileName("Generation.Verify Generated Code NET8")
//#endif
//#if NET9_0
//    settings.UseFileName("Generation.Verify Generated Code NET9")
//#endif
//#if NET10_0
//    settings.UseFileName("Generation.Verify Generated Code NET10")
//#endif
//    settings.UseDirectory("./Verify")
//    settings.ScrubLines(fun line -> line.StartsWith("// This code was generated by"))
//    VerifierSettings.OmitContentFromException() // Cleans up FAKE build output
//    let! _ = Verifier.Verify(code, settings)
//    ()
//}

//[<Test>]
//let ``Code Should Have Reader``() =
//    cfg |> inCode "type HydraReader"

//[<Test>]
//let ``Code Should Not Have Reader``() =
//    { cfg with Readers = None } |> notInCode "type HydraReader"

//[<Test>]
//let ``Code Should Have CLIMutable``() =
//    { cfg with IsCLIMutable = true } |> inCode "[<CLIMutable>]"

//[<Test>]
//let ``Code Should Not Have CLIMutable``() =
//    { cfg with IsCLIMutable = false } |> notInCode "[<CLIMutable>]"

//[<Test>]
//let ``Code Should Have Namespace``() =
//    cfg |> inCode "namespace TestNS"

//[<Test>]
//let ``Should have Tables and PKs``() =
//    let schema = lazySchema.Value
    
//    let allColumns = 
//        schema.Tables 
//        |> List.collect (fun t -> t.Columns)

//    let pks = allColumns |> List.filter (fun c -> c.IsPK)
    
//    schema.Tables.Length >! 0

//    let numberOfTables =
//        schema.Tables
//        |> Seq.filter (fun t -> t.Type = TableType.Table)
//        |> Seq.length

//    Assert.IsTrue(pks.Length > numberOfTables, "Expected at least one pk per table")
//    Assert.IsTrue(pks.Length < allColumns.Length, "Every column should not be a PK")

//[<Test>]
//let ``Code Should Have ProviderDbTypeAttribute With Json``() =
//    cfg |> inCode "[<ProviderDbType(\"Json\")>]"

//[<Test>]
//let ``Code Should Have ProviderDbTypeAttribute With Jsonb``() =
//    cfg |> inCode "[<ProviderDbType(\"Jsonb\")>]"


// Read-only column generation. DB-free: drives SchemaTemplate.generate with a synthetic schema.

let private baseCfg : Config =
    {
        ConnectionString = ""
        OutputFile = ""
        Namespace = "TestNS"
        IsCLIMutable = true
        IsMutableProperties = false
        NullablePropertyType = NullablePropertyType.Option
        ProviderDbTypeAttributes = true
        TableDeclarations = true
        SystemColumns = []
        Readers = None
        Filters = Filters.Empty
        TypeMappingExtensions = []
    }

let private currencycode =
    {
        Column.Name = "currencycode"
        Column.IsNullable = false
        Column.IsPK = true
        Column.Doc = []
        Column.ReadOnly = None
        Column.TypeMapping =
            {
                TypeMapping.ColumnTypeAlias = "character"
                TypeMapping.ClrType = "string"
                TypeMapping.DbType = System.Data.DbType.String
                TypeMapping.ProviderDbType = Some "Char"
            }
    }

/// Stands in for a `GENERATED ALWAYS AS (...) STORED` column as the schema provider marks it.
let private generatedRate =
    {
        Column.Name = "rate"
        Column.IsNullable = false
        Column.IsPK = false
        Column.Doc = []
        Column.ReadOnly = Some ReadOnlyColumn.Generated
        Column.TypeMapping =
            {
                TypeMapping.ColumnTypeAlias = "numeric"
                TypeMapping.ClrType = "decimal"
                TypeMapping.DbType = System.Data.DbType.Decimal
                TypeMapping.ProviderDbType = Some "Numeric"
            }
    }

let private schemaOf columns : Schema =
    {
        Tables =
            [ {
                Table.Catalog = ""
                Table.Schema = "sales"
                Table.Name = "currency"
                Table.Type = TableType.Table
                Table.Columns = currencycode :: columns
                Table.TotalColumns = 1 + List.length columns
              } ]
        Enums = []
    }

let private generateColumns columns =
    let version : Version.InformationalVersion =
        { InformationalVersion = "4.1.0-test"; Version = System.Version(4, 1, 0); PreReleaseSuffix = None }
    SchemaTemplate.generate baseCfg Provider.instance (schemaOf columns) version []

let private generateWith systemColumns =
    generateColumns (systemColumns |> List.map NpgsqlDataTypes.toSystemColumn)

[<Test>]
let ``A generated column is read-only, and stays in SELECT *``() =
    let code = generateColumns [ generatedRate ]
    code.Contains("[<ReadOnlyColumn>]") =! true
    code.Contains("[<SystemColumn>]") =! false

[<Test>]
let ``A system column is excluded from SELECT *, and read-only by inheriting it``() =
    let code = generateWith [ "xmin" ]
    code.Contains("[<SystemColumn>]") =! true
    code.Contains("[<ReadOnlyColumn>]") =! false

[<Test>]
let ``An ordinary column carries neither attribute``() =
    let code = generateWith []
    code.Contains("[<ReadOnlyColumn>]") =! false
    code.Contains("[<SystemColumn>]") =! false

// CLR and provider DB types, verified against a live PostgreSQL.
[<TestCase("tableoid", "tableoid: uint", "Oid")>]
[<TestCase("xmin", "xmin: uint", "Xid")>]
[<TestCase("cmin", "cmin: uint", "Cid")>]
[<TestCase("xmax", "xmax: uint", "Xid")>]
[<TestCase("cmax", "cmax: uint", "Cid")>]
[<TestCase("ctid", "ctid: NpgsqlTypes.NpgsqlTid", "Tid")>]
let ``Each system column generates its own CLR type and provider DB type`` (name: string) (field: string) (providerDbType: string) =
    let code = generateWith [ name ]
    code.Contains(field) =! true
    code.Contains($"[<ProviderDbType(\"{providerDbType}\")>]") =! true

[<Test>]
let ``All six system columns can be generated at once``() =
    let code = generateWith NpgsqlDataTypes.systemColumnNames
    for name in NpgsqlDataTypes.systemColumnNames do
        code.Contains($"{name}: ") =! true

[<Test>]
let ``ctid is generated with the caution that it is not a row identifier``() =
    // The config's reader and `row.ctid`'s reader are different people.
    let code = generateWith [ "ctid" ]
    code.Contains("/// WARNING: not a row identifier.") =! true
    code.Contains("VACUUM FULL") =! true

[<Test>]
let ``A misspelled system column fails generation, naming the six that exist``() =
    // A typo must fail, not silently generate nothing.
    let ex = Assert.Throws<System.Exception>(fun () -> NpgsqlDataTypes.toSystemColumn "xmim" |> ignore)
    ex.Message.Contains("'xmim'") =! true
    ex.Message.Contains("tableoid, xmin, cmin, xmax, cmax, ctid") =! true

[<Test>]
let ``A table declaration is still emitted for a table with a system column``() =
    generateWith([ "xmin" ]).Contains("let currency = table<currency>") =! true

// Which tables a configured system column lands on.

let private configured entries = entries |> List.map NpgsqlSchemaProvider.parseSystemColumn

let private namesFor entries schema table =
    NpgsqlSchemaProvider.systemColumnsFor entries schema table |> List.map (fun col -> col.Name)

[<Test>]
let ``A system column goes only to the table its entry names``() =
    let entries = configured [ "sales/currency.xmin" ]
    namesFor entries "sales" "currency" =! [ "xmin" ]
    namesFor entries "sales" "salesorderheader" =! []
    namesFor entries "person" "currency" =! []

[<Test>]
let ``The table part of an entry is a glob, as it is in the filters``() =
    let entries = configured [ "sales/*.xmin"; "person/address.ctid" ]
    namesFor entries "sales" "currency" =! [ "xmin" ]
    namesFor entries "person" "address" =! [ "ctid" ]
    namesFor entries "person" "person" =! []

[<Test>]
let ``Entries overlapping on one table generate each column once``() =
    let entries = configured [ "sales/currency.xmin"; "sales/*.xmin"; "sales/currency.ctid" ]
    namesFor entries "sales" "currency" =! [ "xmin"; "ctid" ]

[<Test>]
let ``An entry that names no table fails, saying how to name one``() =
    // The shape this had before it was per-table, and the one people will try first.
    let ex = Assert.Throws<System.Exception>(fun () -> NpgsqlSchemaProvider.parseSystemColumn "xmin" |> ignore)
    ex.Message.Contains("{schema}/{table}.{column}") =! true

// Read-only detection against a live PostgreSQL: the four column kinds in one table.

let private readOnlyProbeDdl =
    """
    DROP TABLE IF EXISTS sales.sqlhydra_readonly_probe;
    CREATE TABLE sales.sqlhydra_readonly_probe (
        id    int GENERATED ALWAYS AS IDENTITY,
        seq   int GENERATED BY DEFAULT AS IDENTITY,
        price numeric NOT NULL,
        tax   numeric GENERATED ALWAYS AS (price * 0.1) STORED
    );
    """

let private execute sql =
    use conn = new global.Npgsql.NpgsqlConnection(DB.connectionString)
    conn.Open()
    use cmd = new global.Npgsql.NpgsqlCommand(sql, conn)
    cmd.ExecuteNonQuery() |> ignore

[<Test>]
let ``The schema provider marks the columns PostgreSQL generates, and only those``() =
    execute readOnlyProbeDdl

    try
        let cfg =
            { baseCfg with
                ConnectionString = DB.connectionString
                Filters = { Filters.Empty with Includes = [ "sales/sqlhydra_readonly_probe" ] } }

        // Found by name, not `exactlyOne`: materialized views are appended after
        // `SchemaFilters.filterTables` runs, so the include filter does not narrow them.
        let isReadOnly =
            (NpgsqlSchemaProvider.getSchema(cfg, false, [])).Tables
            |> List.find (fun tbl -> tbl.Name = "sqlhydra_readonly_probe")
            |> fun tbl -> tbl.Columns |> List.map (fun col -> col.Name, col.ReadOnly.IsSome) |> Map.ofList

        isReadOnly["id"] =! true     // GENERATED ALWAYS AS IDENTITY
        isReadOnly["tax"] =! true    // GENERATED ALWAYS AS (...) STORED
        isReadOnly["seq"] =! false   // GENERATED BY DEFAULT AS IDENTITY: writable
        isReadOnly["price"] =! false
    finally
        execute "DROP TABLE IF EXISTS sales.sqlhydra_readonly_probe;"

let private optInProbeDdl =
    """
    DROP TABLE IF EXISTS sales.sqlhydra_optin;
    DROP TABLE IF EXISTS sales.sqlhydra_no_optin;
    CREATE TABLE sales.sqlhydra_optin (id int PRIMARY KEY);
    CREATE TABLE sales.sqlhydra_no_optin (id int PRIMARY KEY);
    """

[<Test>]
let ``A table that does not opt in gets no system column, alongside one that does``() =
    execute optInProbeDdl

    try
        let cfg =
            { baseCfg with
                ConnectionString = DB.connectionString
                SystemColumns = [ "sales/sqlhydra_optin.xmin" ]
                Filters = { Filters.Empty with Includes = [ "sales/sqlhydra_optin"; "sales/sqlhydra_no_optin" ] } }

        let schema = NpgsqlSchemaProvider.getSchema(cfg, false, [])

        let hasXmin name =
            schema.Tables
            |> List.find (fun tbl -> tbl.Name = name)
            |> fun tbl -> tbl.Columns |> List.exists (fun col -> col.Name = "xmin")

        hasXmin "sqlhydra_optin" =! true
        hasXmin "sqlhydra_no_optin" =! false
    finally
        execute "DROP TABLE IF EXISTS sales.sqlhydra_optin; DROP TABLE IF EXISTS sales.sqlhydra_no_optin;"
