module Npgsql.Generation

open Swensen.Unquote
open SqlHydra
open SqlHydra.Domain
open NUnit.Framework
open VerifyTests
open VerifyNUnit
open SqlHydra.Npgsql

//let cfg = 
//    {
//        ConnectionString = DB.connectionString
//        OutputFile = ""
//        Namespace = "TestNS"
//        IsCLIMutable = true
//        IsMutableProperties = false
//        NullablePropertyType = NullablePropertyType.Option
//        ProviderDbTypeAttributes = true
//        TableDeclarations = false
//        Readers = Some { ReadersConfig.ReaderType = Provider.provider.DefaultReaderType } 
//        Filters = Filters.Empty
//    }

//let lazySchema = lazy NpgsqlSchemaProvider.getSchema (cfg, false)

//let getCode cfg =
//    let version = Version.get()
//    SchemaTemplate.generate cfg Provider.provider lazySchema.Value version false

//let inCode (str: string) cfg = 
//    let code = getCode cfg
//    code.Contains str =! true

//let notInCode (str: string) cfg = 
//    let code = getCode cfg
//    code.Contains str =! false

//[<Test; Ignore "Ignore">]
//let ``Print Schema``() =
//    let schema = NpgsqlSchemaProvider.getSchema (cfg, false)
//    printfn "Schema: %A" schema

//[<Test; Ignore "Ignore">]
//let ``Print Code``() =
//    getCode cfg |> printfn "%s"

//[<Test>]
//let ``Verify Generated Code``() = task {
//    let code = getCode cfg
            
//    let settings = VerifySettings()
//#if NET8_0
//    settings.UseFileName("Generation.Verify Generated Code NET8")
//#endif
//#if NET9_0
//    settings.UseFileName("Generation.Verify Generated Code NET9")
//#endif
//#if NET10_0
//    settings.UseFileName("Generation.Verify Generated Code NET10")
//#endif
//    settings.UseDirectory("./Verify")
//    settings.ScrubLines(fun line -> line.StartsWith("// This code was generated by"))
//    VerifierSettings.OmitContentFromException() // Cleans up FAKE build output
//    let! _ = Verifier.Verify(code, settings)
//    ()
//}

//[<Test>]
//let ``Code Should Have Reader``() =
//    cfg |> inCode "type HydraReader"

//[<Test>]
//let ``Code Should Not Have Reader``() =
//    { cfg with Readers = None } |> notInCode "type HydraReader"

//[<Test>]
//let ``Code Should Have CLIMutable``() =
//    { cfg with IsCLIMutable = true } |> inCode "[<CLIMutable>]"

//[<Test>]
//let ``Code Should Not Have CLIMutable``() =
//    { cfg with IsCLIMutable = false } |> notInCode "[<CLIMutable>]"

//[<Test>]
//let ``Code Should Have Namespace``() =
//    cfg |> inCode "namespace TestNS"

//[<Test>]
//let ``Should have Tables and PKs``() =
//    let schema = lazySchema.Value
    
//    let allColumns = 
//        schema.Tables 
//        |> List.collect (fun t -> t.Columns)

//    let pks = allColumns |> List.filter (fun c -> c.IsPK)
    
//    schema.Tables.Length >! 0

//    let numberOfTables =
//        schema.Tables
//        |> Seq.filter (fun t -> t.Type = TableType.Table)
//        |> Seq.length

//    Assert.IsTrue(pks.Length > numberOfTables, "Expected at least one pk per table")
//    Assert.IsTrue(pks.Length < allColumns.Length, "Every column should not be a PK")

//[<Test>]
//let ``Code Should Have ProviderDbTypeAttribute With Json``() =
//    cfg |> inCode "[<ProviderDbType(\"Json\")>]"

//[<Test>]
//let ``Code Should Have ProviderDbTypeAttribute With Jsonb``() =
//    cfg |> inCode "[<ProviderDbType(\"Jsonb\")>]"


// Table filters, against a live PostgreSQL.

let private filterCfg filters : Config =
    {
        ConnectionString = DB.connectionString
        OutputFile = ""
        Namespace = "TestNS"
        IsCLIMutable = true
        IsMutableProperties = false
        NullablePropertyType = NullablePropertyType.Option
        ProviderDbTypeAttributes = true
        TableDeclarations = true
        Readers = None
        Filters = filters
        TypeMappingExtensions = []
    }

let private generatedPaths filters =
    (NpgsqlSchemaProvider.getSchema(filterCfg filters, false, [])).Tables
    |> List.map (fun tbl -> $"{tbl.Schema}/{tbl.Name}")

[<Test>]
let ``Table filters exclude materialized views, which used to bypass them``() =
    // AdventureWorks has two: person/vstateprovincecountryregion and
    // production/vproductanddescription. Both came back whatever the filters said.
    generatedPaths { Filters.Empty with Includes = [ "person/address" ] } =! [ "person/address" ]

[<Test>]
let ``Table filters keep materialized views that match``() =
    let paths = generatedPaths { Filters.Empty with Includes = [ "person/*" ] }
    (paths |> List.contains "person/vstateprovincecountryregion") =! true
    (paths |> List.contains "production/vproductanddescription") =! false

[<Test>]
let ``A wildcard include keeps every relation, materialized views included``() =
    // `include = [ "*" ]` is what the repo's own .toml files use; it must still mean "all".
    let paths = generatedPaths { Filters.Empty with Includes = [ "*" ] }
    (paths |> List.contains "person/address") =! true
    (paths |> List.contains "person/vstateprovincecountryregion") =! true
