// This code was generated by `SqlHydra.Npgsql` -- v3.5.0.
namespace Npgsql.GeneratedTestTypes

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(3, 5, 0)
    let ns = "Npgsql.GeneratedTestTypes"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module ext =
    type mood =
        | sad = 1
        | ok = 2
        | happy = 3


module person =

    [<CLIMutable>]
    type vstateprovincecountryregion =
        { [<ProviderDbType("Integer")>]
          stateprovinceid: Option<int>
          [<ProviderDbType("Name")>]
          stateprovincename: Option<string>
          [<ProviderDbType("Integer")>]
          territoryid: Option<int>
          [<ProviderDbType("Varchar")>]
          countryregioncode: Option<string>
          [<ProviderDbType("Name")>]
          countryregionname: Option<string> }

    let vstateprovincecountryregion = table<vstateprovincecountryregion>

module production =

    [<CLIMutable>]
    type vproductanddescription =
        { [<ProviderDbType("Integer")>]
          productid: Option<int>
          [<ProviderDbType("Name")>]
          name: Option<string>
          [<ProviderDbType("Name")>]
          productmodel: Option<string>
          [<ProviderDbType("Varchar")>]
          description: Option<string> }

    let vproductanddescription = table<vproductanddescription>

module ``public`` =

    [<CLIMutable>]
    type test_articles =
        { [<ProviderDbType("Uuid")>]
          id: System.Guid
          [<ProviderDbType("Uuid")>]
          email_id: System.Guid
          [<ProviderDbType("Varchar")>]
          title: string }

    let test_articles = table<test_articles>

    [<CLIMutable>]
    type test_emails =
        { [<ProviderDbType("Uuid")>]
          id: System.Guid
          [<ProviderDbType("Uuid")>]
          source_id: Option<System.Guid>
          [<ProviderDbType("Uuid")>]
          user_id: Option<System.Guid>
          [<ProviderDbType("Varchar")>]
          sender: string
          [<ProviderDbType("Varchar")>]
          subject: Option<string>
          [<ProviderDbType("Varchar")>]
          status: string
          [<ProviderDbType("Varchar")>]
          owner_type: string
          [<ProviderDbType("TimestampTz")>]
          received_at: System.DateTime
          [<ProviderDbType("Varchar")>]
          chunk_status: Option<string>
          [<ProviderDbType("Bigint")>]
          simhash: Option<int64>
          [<ProviderDbType("TimestampTz")>]
          verified_at: Option<System.DateTime> }

    let test_emails = table<test_emails>

    [<CLIMutable>]
    type test_events =
        { [<ProviderDbType("Uuid")>]
          id: System.Guid
          [<ProviderDbType("Varchar")>]
          email_event_id: Option<string>
          [<ProviderDbType("Uuid")>]
          user_id: System.Guid
          [<ProviderDbType("Varchar")>]
          event_type: string
          [<ProviderDbType("TimestampTz")>]
          created_at: System.DateTime }

    let test_events = table<test_events>

    [<CLIMutable>]
    type test_preferences =
        { [<ProviderDbType("Uuid")>]
          id: System.Guid
          [<ProviderDbType("Uuid")>]
          source_id: System.Guid
          [<ProviderDbType("Uuid")>]
          user_id: System.Guid
          [<ProviderDbType("Integer")>]
          priority: int }

    let test_preferences = table<test_preferences>

    [<CLIMutable>]
    type test_sources =
        { [<ProviderDbType("Uuid")>]
          id: System.Guid
          [<ProviderDbType("Varchar")>]
          name: string
          [<ProviderDbType("TimestampTz")>]
          verified_at: Option<System.DateTime>
          [<ProviderDbType("Integer")>]
          priority: int }

    let test_sources = table<test_sources>


[<System.Obsolete("The HydraReader module is no longer needed and will be removed in v4.0.")>]
type HydraReader =
    static member Read(reader: Microsoft.Data.SqlClient.SqlDataReader) : (unit -> 'T) =
        Hydration.buildRowReader<'T> Domain.ProviderType.Npgsql reader


[<System.Obsolete("The HydraBuilders module is no longer needed and will be removed in v4.0.")>]
module HydraBuilders =
    ()


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        QueryContextFactory.Create(Npgsql.NpgsqlDataSource.Create(connectionString), ?sqlLogger = sqlLogger)

    static member Create(dataSource: Npgsql.NpgsqlDataSource, ?sqlLogger) =
        let compiler = SqlKata.Compilers.PostgresCompiler()

        let createConn () : System.Data.Common.DbConnection = dataSource.OpenConnection()

        let openContext () =
            let conn = createConn ()
            let ctx = new QueryContext(conn, compiler)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let! conn = dataSource.OpenConnectionAsync()
                let ctx = new QueryContext(conn, compiler)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
