<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Support.fs" />
    <Compile Include="SchemaA.fs" />
    <Compile Include="SchemaB.fs" />
    <Compile Include="ConsumerA.fs" />
    <Compile Include="ConsumerB.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SqlHydra.Query\SqlHydra.Query.fsproj" />
    <ProjectReference Include="..\SqlHydra.Domain\SqlHydra.Domain.fsproj" />
  </ItemGroup>
</Project>
