module Spike.Support

open SqlHydra.Query
open Npgsql

let connectionString =
    @"Server=localhost;Port=54320;Database=Adventureworks;User Id=postgres;Password=postgres;Timeout=5"

let emitter = PostgresEmitter() :> ISqlEmitter

let toSql (q: SelectQuery) = (q.CompileWith(emitter)).Sql

let openCtx () =
    let conn = new NpgsqlConnection(connectionString)
    conn.Open()
    let ctx = new QueryContext(conn, emitter)
    ctx.Logger <- (fun cq -> printfn "         SQL: %s" cq.Sql)
    ctx

/// Design A: an erased unit of measure standing for "the database owns this column".
[<Measure>]
type ro

/// Design B: the nominal wrapper, now living in SqlHydra.Domain so hydration can see it.
type ReadOnly<'T> = SqlHydra.ReadOnly<'T>

let exec (ctx: QueryContext) (sql: string) =
    use cmd = ctx.Connection.CreateCommand()
    cmd.CommandText <- sql
    cmd.ExecuteNonQuery() |> ignore

/// Mirrors src/Tests/Npgsql/QueryIntegrationTests.fs ReadOnlyColumnFixture.ddl,
/// plus non-numeric generated columns so coverage can be measured.
let ddl =
    """
    DROP TABLE IF EXISTS sales.spike_readonly;
    CREATE TABLE sales.spike_readonly (
        id     int GENERATED ALWAYS AS IDENTITY,
        seq    int GENERATED BY DEFAULT AS IDENTITY,
        price  numeric NOT NULL,
        code   text NOT NULL,
        tax    numeric GENERATED ALWAYS AS (price * 0.1) STORED,
        label  text GENERATED ALWAYS AS (code || '-gen') STORED,
        dear   boolean GENERATED ALWAYS AS (price > 5) STORED,
        disc   numeric GENERATED ALWAYS AS (nullif(price, 20) * 0.05) STORED
    );
    """

let dropDdl = "DROP TABLE IF EXISTS sales.spike_readonly;"
